ci: GH-3 Part 2 - Fixing workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,5 +17,11 @@ jobs:
         with:
           go-version-file: go.mod
 
-      - name: Verify
-        run: make verify
+      - name: Generate SDK
+        run: make all
+
+      - name: Check for uncommitted changes
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+              echo "::error::SDK changes detected. Make sure you have pushed all generated changes" && exit 1
+          fi
